package v1

import (
	customerController "eniqlo/internal/delivery/http/v1/controller/customer"
	productController "eniqlo/internal/delivery/http/v1/controller/product"
	staffControllers "eniqlo/internal/delivery/http/v1/controller/staff"
	checkoutService "eniqlo/internal/service/checkout"
	customerService "eniqlo/internal/service/customer"
	productService "eniqlo/internal/service/product"
	staffService "eniqlo/internal/service/staff"

	"github.com/go-playground/validator/v10"
	"github.com/jmoiron/sqlx"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "eniqlo/cmd/docs" // docs is generated by Swag CLI, you have to import it.
)

func Init(app *echo.Echo, db *sqlx.DB, val *validator.Validate) {
	var (
		staffSvc    = staffService.New(db)
		productSvc  = productService.New(db)
		customerSvc = customerService.New(db)
		checkoutSvc = checkoutService.New(db)
	)
	v1 := app.Group("/v1")
	staffControllers.Init(v1, val, staffSvc)
	productController.Init(v1, val, productSvc, checkoutSvc)
	customerController.Init(v1, val, customerSvc)
	v1.GET("/swagger/*", echoSwagger.WrapHandler)
}
